version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "tomswartz07"
    reviewers:
      - "tomswartz07"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "tomswartz07"
    reviewers:
      - "tomswartz07"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "tomswartz07"
    reviewers:
      - "tomswartz07"
